#!/usr/bin/env bash
# SSH client configuration

Host web-01
	Hostname 54.175.147.49
	User ubuntu
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
        SendEnv LANG LC_*
        HashKnownHosts yes
        GSSAPIAuthentication yes
        GSSAPIDelegateCredentials no


